name: trenchbroom
version: v2021.1
grade: stable
summary: A modern cross-platform level editor for Quake-engine based games.
description: |
  TrenchBroom is a cross platform level editor for Quake-engine based games.
  It supports Quake, Quake 2, Quake 3 and Hexen 2 and runs on Windows (XP and newer),
  Mac OS X (10.6 and newer) and Linux. TrenchBroom is easy to use and provides
  many simple and advanced tools to create complex and interesting levels with ease.
  
  General
    - Full support for editing in 3D and in up to three 2D views
    - High performance renderer with support for huge maps
    - Unlimited Undo and Redo
    - Macro-like command repetition
    - Issue browser with automatic quick fixes
    - Point file support
    - Automatic backups
    - Free and cross platform
  Brush Editing
    - Robust vertex editing with edge and face splitting and manipulating multiple vertices together
    - Clipping tool with two and three points
    - CSG operations: merge, subtract, intersect
    - UV view for easy texture manipulations
    - Precise texture lock for all brush editing operations
    - Multiple texture collections
  Entity Editing
    - Entity browser with drag and drop support
    - Support for FGD and DEF files for entity definitions
    - Mod support
    - Entity link visualization
    - Displays 3D models in the editor
    - Smart entity property editors
    
  To enable Quake engines within the editor install and connect an engine:
  
    # Quake 1 support
    snap install quakespasm-beidl # or vkquake
    snap connect trenchbroom:quake-engine quakespasm-beidl:quake-engine
    
    # Quake 2 support
    snap install yamagi-quake2-beidl
    snap connect trenchbroom:quake2-engine yamagi-quake2-beidl:quake2-engine
  
  The engine will be available at one of these locations:
    /snap/trenchbroom/current/quake-engine/
    /snap/trenchbroom/current/quake2-engine/
  Or:
    /var/lib/snapd/snap/trenchbroom/current/quake-engine/
    /var/lib/snapd/snap/trenchbroom/current/quake2-engine/

confinement: strict
base: core20

apps:
  trenchbroom:
    command: bin/desktop-launch trenchbroom
    plugs: [ x11, desktop, opengl, pulseaudio, home, removable-media ]

plugs:
  quake-modtools:
    content: quake-modtools
    interface: content
    target: $SNAP/quaketools
    default-provider: quake-toolkit:quake-modtools
  quake-engine:
    content: quake-engine
    interface: content
    target: $SNAP/quake-engine
  quake2-engine:
    content: quake2-engine
    interface: content
    target: $SNAP/quake2-engine
  quake3-engine:
    content: quake3-engine
    interface: content
    target: $SNAP/quake3-engine

parts:
  desktop-qt5:
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    make-parameters:
      - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5
      - locales-all
      - xdg-user-dirs
      - libopengl0
  trenchbroom:
    source: https://github.com/kduske/TrenchBroom.git
    source-type: git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    plugin: cmake
    override-build: |
      if [ -d "$SNAPCRAFT_PART_BUILD/build" ]; then
          rm -rf "$SNAPCRAFT_PART_BUILD/build"
      fi
      mkdir "$SNAPCRAFT_PART_BUILD/build"
      cd "$SNAPCRAFT_PART_BUILD/build"
      cmake "$SNAPCRAFT_PART_SRC" -DCMAKE_BUILD_TYPE=Release
      cmake --build . --target TrenchBroom-nomanual --parallel $(nproc --all)
      cp -a "$SNAPCRAFT_PART_BUILD/build/app/trenchbroom-nomanual" "$SNAPCRAFT_PART_BUILD/build/app/trenchbroom"
      mkdir "$SNAPCRAFT_PART_BUILD/build/app/manual"
      cmake --install . --prefix "$SNAPCRAFT_PART_INSTALL"
    build-packages:
      - qt5-default
      - libqt5svg5-dev
      - freeglut3-dev
      - libglew-dev
      - mesa-common-dev
      - build-essential
      - libglm-dev
      - libxxf86vm-dev
      - libfreeimage-dev
      - libfreetype6-dev
      - pandoc
      - cmake
      - p7zip-full
      - ninja-build
    after: [ desktop-qt5 ]
